import { DatabaseAdapter } from "./database/adapter";
import { logger } from "@/utils/logger";

export interface Migration {
  id: string;
  sql?: {
    postgres: string;
    sqlite: string;
  };
  execFn?: (db: DatabaseAdapter) => Promise<void>;
}

export async function runMigrations(db: DatabaseAdapter): Promise<void> {
  // Create migrations tracking table
  const createMigrationsTable =
    db.type === "postgres"
      ? `CREATE TABLE IF NOT EXISTS _migrations (
           id TEXT PRIMARY KEY,
           applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
         );`
      : `CREATE TABLE IF NOT EXISTS _migrations (
           id TEXT PRIMARY KEY,
           applied_at TEXT NOT NULL DEFAULT (datetime('now'))
         );`;

  await db.query(createMigrationsTable);

  const result = await db.query<{ id: string }>("SELECT id FROM _migrations");
  const applied = new Set(result.rows.map((row) => row.id));

  for (const migration of migrations) {
    if (applied.has(migration.id)) {
      logger.debug(`Migration ${migration.id} already applied, skipping`);
      continue;
    }

    logger.info(`Running migration: ${migration.id}`);

    if (migration.sql) {
      await db.query(migration.sql[db.type]);
    }

    if (migration.execFn) {
      await migration.execFn(db);
    }

    await db.query("INSERT INTO _migrations (id) VALUES ($1)", [migration.id]);

    logger.info(`Migration ${migration.id} completed`);
  }
}

export const migrations: Migration[] = [
  {
    id: "001_create_users_table",
    sql: {
      postgres: `
        CREATE TABLE IF NOT EXISTS l_users (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          pubkey TEXT NOT NULL UNIQUE,
          name TEXT UNIQUE,
          mint_url TEXT,
          lock_quote BOOLEAN DEFAULT FALSE
        );
      `,
      sqlite: `
        CREATE TABLE IF NOT EXISTS l_users (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          created_at TEXT NOT NULL DEFAULT (datetime('now')),
          pubkey TEXT NOT NULL UNIQUE,
          name TEXT UNIQUE,
          mint_url TEXT,
          lock_quote INTEGER DEFAULT 0
        );
      `,
    },
  },
  {
    id: "002_create_mint_quotes_table",
    sql: {
      postgres: `
        CREATE TABLE IF NOT EXISTS mint_quotes (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          unit TEXT NOT NULL,
          mint_url TEXT NOT NULL,
          payment_request TEXT NOT NULL,
          quote_id TEXT NOT NULL,
          expires_at TIMESTAMPTZ NOT NULL,
          amount INTEGER NOT NULL,
          pubkey TEXT NOT NULL,
          state TEXT NOT NULL,
          paid_at TIMESTAMPTZ,
          serialized_zap_request TEXT,
          locked BOOLEAN NOT NULL DEFAULT FALSE
        );
        CREATE INDEX IF NOT EXISTS idx_mint_quotes_quote_id ON mint_quotes(quote_id);
      `,
      sqlite: `
        CREATE TABLE IF NOT EXISTS mint_quotes (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          created_at TEXT NOT NULL DEFAULT (datetime('now')),
          unit TEXT NOT NULL,
          mint_url TEXT NOT NULL,
          payment_request TEXT NOT NULL,
          quote_id TEXT NOT NULL,
          expires_at TEXT NOT NULL,
          amount INTEGER NOT NULL,
          pubkey TEXT NOT NULL,
          state TEXT NOT NULL,
          paid_at TEXT,
          serialized_zap_request TEXT,
          locked INTEGER NOT NULL DEFAULT 0
        );
        CREATE INDEX IF NOT EXISTS idx_mint_quotes_quote_id ON mint_quotes(quote_id);
      `,
    },
  },
  {
    id: "003_create_mints_table",
    sql: {
      postgres: `
        CREATE TABLE IF NOT EXISTS mints (
          mint_url TEXT PRIMARY KEY,
          last_checked TIMESTAMPTZ NOT NULL,
          mint_info JSONB NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_mints_mint_url ON mints(mint_url);
      `,
      sqlite: `
        CREATE TABLE IF NOT EXISTS mints (
          mint_url TEXT PRIMARY KEY,
          last_checked TEXT NOT NULL,
          mint_info TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_mints_mint_url ON mints(mint_url);
      `,
    },
  },
  {
    id: "004_fix_zap_request_column_typo",
    // Only runs if the typo column exists (v2 upgrade), skips for fresh installs
    execFn: async (db) => {
      if (db.type === "postgres") {
        const result = await db.query<{ column_name: string }>(`
          SELECT column_name FROM information_schema.columns
          WHERE table_name = 'mint_quotes' AND column_name = 'serialzed_zap_request'
        `);
        if (result.rows.length > 0) {
          await db.query(`
            ALTER TABLE mint_quotes
            RENAME COLUMN serialzed_zap_request TO serialized_zap_request
          `);
        }
      } else {
        // SQLite: check via pragma
        const result = await db.query<{ name: string }>(`
          PRAGMA table_info(mint_quotes)
        `);
        const hasTypoColumn = result.rows.some((r) => r.name === "serialzed_zap_request");
        if (hasTypoColumn) {
          await db.query(`
            ALTER TABLE mint_quotes
            RENAME COLUMN serialzed_zap_request TO serialized_zap_request
          `);
        }
      }
    },
  },
  {
    id: "005_create_proofs_table",
    sql: {
      postgres: `
        CREATE TABLE IF NOT EXISTS proofs (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          amount INTEGER NOT NULL,
          keyset_id TEXT NOT NULL,
          secret TEXT NOT NULL,
          "C" TEXT NOT NULL,
          state TEXT NOT NULL
        );
      `,
      sqlite: `
        CREATE TABLE IF NOT EXISTS proofs (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          amount INTEGER NOT NULL,
          keyset_id TEXT NOT NULL,
          secret TEXT NOT NULL,
          C TEXT NOT NULL,
          state TEXT NOT NULL
        );
      `,
    },
  },
  {
    id: "006_add_auto_store_to_mint_quotes",
    sql: {
      postgres: `
        ALTER TABLE mint_quotes ADD COLUMN IF NOT EXISTS auto_stored_at TIMESTAMPTZ;
        ALTER TABLE mint_quotes ADD COLUMN IF NOT EXISTS auto_store_attempts INTEGER NOT NULL DEFAULT 0;
        ALTER TABLE mint_quotes ADD COLUMN IF NOT EXISTS claim_id BIGINT;
      `,
      sqlite: ``,
    },
    execFn: async (db) => {
      if (db.type !== "sqlite") return;
      const cols = await db.query<{ name: string }>(
        `PRAGMA table_info(mint_quotes)`,
      );
      const names = new Set(cols.rows.map((r) => r.name));
      if (!names.has("auto_stored_at")) {
        await db.query(
          `ALTER TABLE mint_quotes ADD COLUMN auto_stored_at TEXT`,
        );
      }
      if (!names.has("auto_store_attempts")) {
        await db.query(
          `ALTER TABLE mint_quotes ADD COLUMN auto_store_attempts INTEGER NOT NULL DEFAULT 0`,
        );
      }
      if (!names.has("claim_id")) {
        await db.query(
          `ALTER TABLE mint_quotes ADD COLUMN claim_id INTEGER`,
        );
      }
    },
  },
  {
    id: "007_add_claim_storage_mode_to_users",
    sql: {
      postgres: `
        ALTER TABLE l_users ADD COLUMN IF NOT EXISTS claim_storage_mode TEXT NOT NULL DEFAULT 'off';
      `,
      sqlite: `
        ALTER TABLE l_users ADD COLUMN claim_storage_mode TEXT NOT NULL DEFAULT 'off';
      `,
    },
  },
  {
    id: "008_create_claims_table",
    sql: {
      postgres: `
        CREATE TABLE IF NOT EXISTS l_claims (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          user_pubkey TEXT NOT NULL,
          mint_url TEXT NOT NULL,
          proof JSONB NOT NULL,
          status TEXT NOT NULL DEFAULT 'ready',
          quote_id TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          claimed_at TIMESTAMPTZ
        );
        CREATE INDEX IF NOT EXISTS idx_l_claims_user_pubkey_status ON l_claims(user_pubkey, status);
      `,
      sqlite: `
        CREATE TABLE IF NOT EXISTS l_claims (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          user_pubkey TEXT NOT NULL,
          mint_url TEXT NOT NULL,
          proof TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'ready',
          quote_id TEXT,
          created_at TEXT NOT NULL DEFAULT (datetime('now')),
          claimed_at TEXT
        );
      `,
    },
    execFn: async (db) => {
      if (db.type !== "sqlite") return;
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_l_claims_user_pubkey_status ON l_claims(user_pubkey, status)`,
      );
    },
  },
  {
    id: "009_add_last_auto_store_attempt_at",
    sql: {
      postgres: `
        ALTER TABLE mint_quotes ADD COLUMN IF NOT EXISTS last_auto_store_attempt_at TIMESTAMPTZ;
      `,
      sqlite: `
        ALTER TABLE mint_quotes ADD COLUMN last_auto_store_attempt_at TEXT;
      `,
    },
  },
  {
    id: "010_add_relays_to_users",
    sql: {
      postgres: `
        ALTER TABLE l_users ADD COLUMN IF NOT EXISTS relays JSONB NOT NULL DEFAULT '[]';
      `,
      sqlite: `
        ALTER TABLE l_users ADD COLUMN relays TEXT NOT NULL DEFAULT '[]';
      `,
    },
  },
];
